cache:
    directories:
        - $HOME/perl_modules
        - $HOME/tidyall_d

sudo: false
addons:
    apt:
        packages:
            - build-essential
            - gir1.2-json-1.0
            - gobject-introspection
            - libgtk-3-bin
            - libgtk-3-dev
            - libhunspell-dev
            - libjson-glib-dev
            - json-glib-tools
            - meson
            - ninja-build
            - python3-pip
            - python3-setuptools
language: perl
perl:
    - '5.30'
dist: bionic
os: linux
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - cpanm --local-lib=~/perl_modules local::lib
    - eval "$(perl -I ~/perl_modules/lib/perl5 -Mlocal::lib=$HOME/perl_modules)"
install:
    # Failing tests, see:
    # https://github.com/atoomic/perl-TimeDate/issues/40
    - cpanm --quiet --notest Date::Format
    - cpanm --quiet --skip-satisfied Dist::Zilla Pod::Weaver::Section::Support Perl::Critic Perl::Tidy Test::Code::TidyAll
    - export _dzil_dirs="App-gimpgitbuild"
    - "for d in $_dzil_dirs ; do (cd \"$d\" && dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet) ; done"
    - "for d in $_dzil_dirs ; do (cd \"$d\" && dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose) ; done"
    - sudo python3 -m pip install meson
script:
    - "for d in $_dzil_dirs ; do (cd \"$d\" && dzil smoke --release --author && dzil install) || exit -1 ; done"
    - "gimpgitbuild build"
